# Generated by Django 3.1 on 2020-08-26 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='service.city')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.coordinate')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('polygon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.polygon')),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='service.district')),
                ('polygon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.polygon')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='polygon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.polygon'),
        ),
        migrations.AddField(
            model_name='district',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='county', to='service.county'),
        ),
        migrations.AddField(
            model_name='county',
            name='polygon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.polygon'),
        ),
        migrations.AddField(
            model_name='city',
            name='polygon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.polygon'),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='region', to='service.region'),
        ),
    ]
