# Generated by Django 3.1 on 2020-08-22 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('coordinate', models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='service.coordinate', verbose_name='coordinate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('coordinate', models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='service.coordinate', verbose_name='coordinate')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='town', to='service.district')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region', to='service.city')),
                ('coordinate', models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='service.coordinate', verbose_name='coordinate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('coordinate', models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='service.coordinate', verbose_name='coordinate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='district',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='service.neighborhood'),
        ),
        migrations.AddField(
            model_name='city',
            name='coordinate',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='service.coordinate', verbose_name='coordinate'),
        ),
        migrations.AddField(
            model_name='city',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='service.town'),
        ),
    ]
