# Generated by Django 3.1 on 2020-08-28 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region', to='service.region'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='coordinate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.coordinate'),
        ),
    ]
