# Generated by Django 3.1 on 2020-08-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='coordinate',
        ),
        migrations.RemoveField(
            model_name='district',
            name='coordinate',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='coordinate',
        ),
        migrations.RemoveField(
            model_name='region',
            name='coordinate',
        ),
        migrations.RemoveField(
            model_name='town',
            name='coordinate',
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate', models.ManyToManyField(blank=True, to='service.Coordinate')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='polygon',
            field=models.ManyToManyField(blank=True, to='service.Polygon', verbose_name='polygon'),
        ),
        migrations.AddField(
            model_name='district',
            name='polygon',
            field=models.ManyToManyField(blank=True, to='service.Polygon', verbose_name='polygon'),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='polygon',
            field=models.ManyToManyField(blank=True, to='service.Polygon', verbose_name='polygon'),
        ),
        migrations.AddField(
            model_name='region',
            name='polygon',
            field=models.ManyToManyField(blank=True, to='service.Polygon', verbose_name='polygon'),
        ),
        migrations.AddField(
            model_name='town',
            name='polygon',
            field=models.ManyToManyField(blank=True, to='service.Polygon', verbose_name='polygon'),
        ),
    ]
