# Generated by Django 3.1 on 2020-08-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20200824_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='coordinate',
            field=models.ManyToManyField(to='service.Coordinate'),
        ),
    ]
