# Generated by Django 3.1 on 2020-08-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20200820_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='district',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='region',
            name='test',
        ),
        migrations.RemoveField(
            model_name='town',
            name='coordinates',
        ),
        migrations.AlterField(
            model_name='region',
            name='coordinates',
            field=models.ManyToManyField(related_name='region', to='service.Coordinate', verbose_name='coordinate'),
        ),
    ]
