# Generated by Django 3.1 on 2020-08-30 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20200828_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='town',
            new_name='county',
        ),
    ]
