# Generated by Django 3.1 on 2020-08-31 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20200830_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='polygon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.polygon'),
        ),
    ]
