# Generated by Django 3.1 on 2020-08-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20200831_0610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='region',
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ManyToManyField(blank=True, to='service.Region'),
        ),
        migrations.RemoveField(
            model_name='county',
            name='city',
        ),
        migrations.AddField(
            model_name='county',
            name='city',
            field=models.ManyToManyField(blank=True, to='service.City'),
        ),
        migrations.RemoveField(
            model_name='district',
            name='county',
        ),
        migrations.AddField(
            model_name='district',
            name='county',
            field=models.ManyToManyField(blank=True, to='service.County'),
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='district',
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='district',
            field=models.ManyToManyField(blank=True, to='service.District'),
        ),
    ]
