# Generated by Django 3.1 on 2020-08-20 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20200820_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='coordinates',
        ),
    ]
