# Generated by Django 3.1 on 2020-08-31 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20200831_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='polygon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.polygon'),
        ),
    ]
