# Generated by Django 3.1 on 2020-08-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20200831_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='coordinate',
            field=models.ManyToManyField(null=True, to='service.Coordinate'),
        ),
    ]
