# Generated by Django 3.1 on 2020-08-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20200831_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='coordinate',
            field=models.ManyToManyField(blank=True, to='service.Coordinate'),
        ),
    ]
