# Generated by Django 3.1 on 2020-08-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20200831_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='polygon',
        ),
        migrations.AddField(
            model_name='region',
            name='polygon',
            field=models.ManyToManyField(blank=True, to='service.Polygon'),
        ),
    ]
