# Generated by Django 3.1 on 2020-08-31 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20200831_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='polygon',
        ),
        migrations.AddField(
            model_name='city',
            name='polygon',
            field=models.ManyToManyField(blank=True, to='service.Polygon'),
        ),
        migrations.RemoveField(
            model_name='city',
            name='region',
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.region'),
        ),
        migrations.RemoveField(
            model_name='county',
            name='city',
        ),
        migrations.AddField(
            model_name='county',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.city'),
        ),
        migrations.RemoveField(
            model_name='county',
            name='polygon',
        ),
        migrations.AddField(
            model_name='county',
            name='polygon',
            field=models.ManyToManyField(blank=True, to='service.Polygon'),
        ),
        migrations.RemoveField(
            model_name='district',
            name='county',
        ),
        migrations.AddField(
            model_name='district',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.county'),
        ),
        migrations.RemoveField(
            model_name='district',
            name='polygon',
        ),
        migrations.AddField(
            model_name='district',
            name='polygon',
            field=models.ManyToManyField(blank=True, to='service.Polygon'),
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='district',
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.district'),
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='polygon',
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='polygon',
            field=models.ManyToManyField(blank=True, to='service.Polygon'),
        ),
    ]
