# Generated by Django 3.1 on 2020-09-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_auto_20200831_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='polygon',
        ),
        migrations.RemoveField(
            model_name='county',
            name='polygon',
        ),
        migrations.RemoveField(
            model_name='district',
            name='polygon',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='polygon',
        ),
        migrations.RemoveField(
            model_name='region',
            name='polygon',
        ),
        migrations.AddField(
            model_name='city',
            name='coordinate',
            field=models.ManyToManyField(blank=True, to='service.Coordinate'),
        ),
        migrations.AddField(
            model_name='county',
            name='coordinate',
            field=models.ManyToManyField(blank=True, to='service.Coordinate'),
        ),
        migrations.AddField(
            model_name='district',
            name='coordinate',
            field=models.ManyToManyField(blank=True, to='service.Coordinate'),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='coordinate',
            field=models.ManyToManyField(blank=True, to='service.Coordinate'),
        ),
        migrations.AddField(
            model_name='region',
            name='coordinate',
            field=models.ManyToManyField(blank=True, to='service.Coordinate'),
        ),
    ]
