# Generated by Django 3.1 on 2020-09-04 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_auto_20200904_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='coordinate',
            new_name='coordinates',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='coordinate',
            new_name='coordinates',
        ),
        migrations.RenameField(
            model_name='neighborhood',
            old_name='coordinate',
            new_name='coordinates',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='coordinate',
            new_name='coordinates',
        ),
    ]
