# Generated by Django 3.1 on 2020-09-05 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_auto_20200904_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinate',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='coordinate',
            old_name='longitude',
            new_name='lng',
        ),
    ]
