# Generated by Django 3.1 on 2020-09-07 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_auto_20200905_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='district',
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.county'),
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
