# Generated by Django 3.1 on 2020-09-10 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_auto_20200907_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='county',
            old_name='coordinate',
            new_name='coordinates',
        ),
    ]
