# Generated by Django 3.1 on 2020-09-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_auto_20200915_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='city',
            name='coordinates',
            field=models.ManyToManyField(blank=True, to='service.Coordinate'),
        ),
        migrations.RemoveField(
            model_name='county',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='county',
            name='coordinates',
            field=models.ManyToManyField(blank=True, to='service.Coordinate'),
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='coordinates',
            field=models.ManyToManyField(blank=True, to='service.Coordinate'),
        ),
        migrations.RemoveField(
            model_name='region',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='region',
            name='coordinates',
            field=models.ManyToManyField(blank=True, to='service.Coordinate'),
        ),
    ]
