# Generated by Django 3.1 on 2020-08-19 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region', to='service.region', verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='district',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='town', to='service.town', verbose_name='town'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='service.district', verbose_name='district'),
        ),
        migrations.AlterField(
            model_name='town',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='service.city', verbose_name='city'),
        ),
    ]
