# Generated by Django 3.1 on 2020-08-20 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20200819_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='test',
            field=models.CharField(default='string', max_length=20),
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='service.region', verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='district',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='service.town', verbose_name='town'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhood', to='service.district', verbose_name='district'),
        ),
        migrations.AlterField(
            model_name='town',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='town', to='service.city', verbose_name='city'),
        ),
    ]
