# Generated by Django 3.1 on 2020-08-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20200820_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='coordinates',
            field=models.ManyToManyField(related_name='region', to='service.Coordinate', verbose_name='coordinates'),
        ),
    ]
